# Generated by Django 5.0.2 on 2024-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_name', models.CharField(max_length=30)),
                ('text_content', models.CharField(max_length=255)),
            ],
        ),
    ]
