# Generated by Django 5.0.2 on 2024-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_text_name', models.CharField(max_length=30)),
                ('about_text_txt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_text_name', models.CharField(max_length=30)),
                ('contact_text_txt', models.TextField()),
            ],
        ),
    ]
