# Generated by Django 5.0.2 on 2024-03-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_brand', models.CharField(max_length=30)),
                ('prod_model', models.CharField(max_length=30)),
                ('prod_price', models.IntegerField()),
                ('prod_img', models.CharField(max_length=30)),
            ],
        ),
    ]
