# Generated by Django 5.0.2 on 2024-03-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
